In [477]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

In [478]:
base_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_the_2000s"

In [479]:
src = requests.get(base_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [480]:
soup = BeautifulSoup(src.content, 'lxml')

In [481]:
tab_tag = soup.find_all('table', {'class':'wikitable'})
len(tab_tag)

10

In [482]:
lst = []

In [483]:
df = pd.DataFrame()

In [484]:
count = np.arange(10)
print(count)

[0 1 2 3 4 5 6 7 8 9]


In [485]:
for i in count:
    tab_ = pd.read_html(str(tab_tag[i]))
    df_ = pd.DataFrame(tab_[0])
    df = pd.concat([df, df_], axis = 0)

In [486]:
movie_title = [x for x in df['Title']]

In [487]:
movie_title.remove('2000')
movie_title.remove('2001')
movie_title.remove('2002')
movie_title.remove('2003')
movie_title.remove('2004')
movie_title.remove('2005')
movie_title.remove('2006')
movie_title.remove('2007')
movie_title.remove('2008')
movie_title.remove('2009')

In [488]:
# movie_title

In [489]:
# 2010

In [490]:
base_ten_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2010"

In [491]:
src = requests.get(base_ten_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [492]:
soup = BeautifulSoup(src.content, 'lxml')

In [493]:
tab_ten = soup.find_all('table', {'class':'wikitable'})

In [494]:
df_ = pd.read_html(str(tab_ten[0]))
df_ten = pd.DataFrame(df_[0])

In [495]:
ten_list = [x for x in df_ten['Title']]
movie_title = movie_title + ten_list

In [496]:
movie_title[:10]

['Abandonada',
 'Akin Ang Labang Ito',
 'Anak',
 'Ang Dalubhasa',
 'Anghel Dela Guardia',
 'Arayyy!',
 'Baliktaran',
 'Basta Tricycle Driver... Sweet Lover',
 'Birthday Gift 2',
 'Biyaheng Langit']

In [497]:
# 2011

In [498]:
base_ele_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2011"

In [499]:
src = requests.get(base_ele_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [500]:
soup = BeautifulSoup(src.content, 'lxml')

In [501]:
tab_ele = soup.find_all('table', {'class':'wikitable'})

In [502]:
df_ = pd.read_html(str(tab_ele[1]))
df_ele = pd.DataFrame(df_[0])

In [503]:
ele_list = [x for x in df_ele['Title']]
movie_title = movie_title + ele_list

In [504]:
movie_title[-10:]

['Third World Happy',
 'Tum: My Pledge of Love',
 'Tween Academy: Class of 2012',
 'Tumbok',
 'Way Back Home',
 'Wedding Tayo, Wedding Hindi',
 "Who's That Girl",
 "Won't Last A Day Without You",
 'Yesterday, Today, Tomorrow',
 'Zombadings 1: Patayin sa Shokot si Remington']

In [505]:
# 2012

In [506]:
base_twl_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2012"

In [507]:
src = requests.get(base_twl_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [508]:
soup = BeautifulSoup(src.content, 'lxml')

In [509]:
tab_twl = soup.find_all('table', {'class':'wikitable'})

In [510]:
count_ = np.arange(1,5)

In [511]:
df_s = pd.DataFrame()

In [512]:
print(count_)

[1 2 3 4]


In [513]:
for i in count_:
    tab_ = pd.read_html(str(tab_twl[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [514]:
twl_list = [x for x in df_s['Title']]

In [515]:
movie_title += twl_list

In [516]:
movie_title[-10:]

['Flames of Love',
 'MNL 143',
 'Si Agimat, Si Enteng, at Si Ako',
 'El Presidente',
 'One More Try',
 'Shake, Rattle & Roll 14',
 'Sisterakas',
 'Sosy Problems',
 'The Strangers',
 'Thy Womb']

In [517]:
# 2013

In [518]:
base_trt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2013"

In [519]:
src = requests.get(base_trt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [520]:
soup = BeautifulSoup(src.content, 'lxml')

In [521]:
tab_trt = soup.find_all('table', {'class':'wikitable'})

In [522]:
count_ = np.arange(1,5)

In [523]:
df_s = pd.DataFrame()

In [524]:
print(count_)

[1 2 3 4]


In [525]:
for i in count_:
    tab_ = pd.read_html(str(tab_trt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [526]:
trt_list = [x for x in df_s['Title']]

In [527]:
movie_title += trt_list

In [528]:
movie_title[-10:]

['How to Disappear Completely1',
 'Boogie1',
 'Girl, Boy, Bakla, Tomboy',
 'My Little Bossings',
 'Kimmy Dora: Ang Kiyemeng Prequel',
 'Pagpag: Siyam na Buhay',
 '10,000 Hours',
 'Pedro Calungsod: Batang Martir',
 'Boy Golden: Shoot to Kill, the Arturo Porcuna Story',
 'Kaleidoscope World']

In [529]:
# 2014

In [530]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2014"

In [531]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [532]:
soup = BeautifulSoup(src.content, 'lxml')

In [533]:
tab_frt = soup.find_all('table', {'class':'wikitable'})

In [534]:
count_ = np.arange(1,5)

In [535]:
df_s = pd.DataFrame()

In [536]:
print(count_)

[1 2 3 4]


In [537]:
for i in count_:
    tab_ = pd.read_html(str(tab_frt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [538]:
frt_list = [x for x in df_s['Title']]

In [539]:
movie_title += frt_list

In [540]:
movie_title[-10:]

['Mulat',
 'Gangster Lolo',
 'Bonifacio: Ang Unang Pangulo',
 'English Only, Please',
 'Feng Shui 2',
 'Kubot: The Aswang Chronicles 2',
 'Magnum Muslim.357',
 'My Big Bossing',
 'The Amazing Praybeyt Benjamin',
 'Shake, Rattle & Roll XV']

In [541]:
# 2015

In [542]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2015"

In [543]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [544]:
soup = BeautifulSoup(src.content, 'lxml')

In [545]:
tab_ftn = soup.find_all('table', {'class':'wikitable'})

In [546]:
count_ = np.arange(1,5)

In [547]:
df_s = pd.DataFrame()

In [548]:
print(count_)

[1 2 3 4]


In [549]:
for i in count_:
    tab_ = pd.read_html(str(tab_ftn[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [550]:
ftn_list = [x for x in df_s['Title']]

In [551]:
movie_title += ftn_list

In [552]:
movie_title[-10:]

['Toto',
 'Turo-Turo',
 'All You Need Is Pag-Ibig',
 'Beauty and the Bestie',
 'Buy Now, Die Later',
 'Haunted Mansion',
 'Honor Thy Father',
 'My Bebe Love: #KiligPaMore',
 'Nilalang',
 '#Walang Forever']

In [553]:
# 2016

In [554]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2016"

In [555]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [556]:
soup = BeautifulSoup(src.content, 'lxml')

In [557]:
tab_sx = soup.find_all('table', {'class':'wikitable'})

In [558]:
count_ = np.arange(1,5)

In [559]:
df_s = pd.DataFrame()

In [560]:
print(count_)

[1 2 3 4]


In [561]:
for i in count_:
    tab_ = pd.read_html(str(tab_sx[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [562]:
sx_list = [x for x in df_s['Title']]

In [563]:
movie_title += sx_list

In [564]:
movie_title[-10:]

['Enteng Kabisote 10 and the Abangers',
 'Mano Po 7: Tsinoy',
 'Ang Babae sa Septic Tank 2: #ForeverIsNotEnough',
 'Die Beautiful',
 'Kabisera',
 'Oro',
 'Saving Sally',
 'Seklusyon',
 'Sunday Beauty Queen',
 'Vince & Kath & James']

In [565]:
# 2017

In [566]:
base_svt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2017"

In [567]:
src = requests.get(base_svt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [568]:
soup = BeautifulSoup(src.content, 'lxml')

In [569]:
tab_svt = soup.find_all('table', {'class':'wikitable'})

In [570]:
count_ = np.arange(1,5)

In [571]:
df_s = pd.DataFrame()

In [572]:
print(count_)

[1 2 3 4]


In [573]:
for i in count_:
    tab_ = pd.read_html(str(tab_svt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [574]:
svt_list = [x for x in df_s['Title']]

In [575]:
movie_title += svt_list

In [576]:
movie_title[-10:]

['Kamandag ng Droga',
 'Smaller and Smaller Circles',
 'All of You',
 'Deadma Walking',
 'Gandarrapiddo: The Revenger Squad',
 'Haunted Forest',
 'Ang Larawan',
 'Meant to Beh',
 'Ang Panday',
 'Siargao']

In [577]:
# 2018

In [578]:
base_eth_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2018"

In [579]:
src = requests.get(base_eth_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [580]:
soup = BeautifulSoup(src.content, 'lxml')

In [581]:
tab_eth = soup.find_all('table', {'class':'wikitable'})

In [582]:
count_ = np.arange(1,5)

In [583]:
df_s = pd.DataFrame()

In [584]:
print(count_)

[1 2 3 4]


In [585]:
for i in count_:
    tab_ = pd.read_html(str(tab_eth[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [586]:
eth_list = [x for x in df_s['Title']]

In [587]:
movie_title += eth_list

In [588]:
movie_title[-10:]

['Kahit Ayaw Mo Na',
 'Everybody Loves Baby Wendy',
 'Aurora',
 'Fantastica: The Princesses, The Prince and The Perya',
 'The Girl in the Orange Dress',
 'Jack Em Popoy: The Puliscredibles',
 'Mary, Marry Me',
 'One Great Love',
 'Otlum',
 "Rainbow's Sunset"]

In [589]:
# 2019

In [590]:
base_nth_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2019"

In [591]:
src = requests.get(base_nth_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [592]:
soup = BeautifulSoup(src.content, 'lxml')

In [593]:
tab_nth = soup.find_all('table', {'class':'wikitable'})

In [594]:
count_ = np.arange(1,5)

In [595]:
df_s = pd.DataFrame()

In [596]:
print(count_)

[1 2 3 4]


In [597]:
for i in count_:
    tab_ = pd.read_html(str(tab_nth[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [598]:
nth_list = [x for x in df_s['Title']]

In [599]:
movie_title += nth_list

In [600]:
movie_title[-10:]

['Sunod',
 'Miracle in Cell No.7',
 'Mission Unstapabol: The Don Identity',
 'The Mall, The Merrier',
 'Mindanao',
 '3pol Trobol: Huli Ka Balbon',
 'Culion',
 'Write About Love',
 nan,
 nan]

In [601]:
# 2020

In [602]:
base_twy_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2020"

In [603]:
src = requests.get(base_twy_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [604]:
soup = BeautifulSoup(src.content, 'lxml')

In [605]:
tab_twy = soup.find_all('table', {'class':'wikitable'})

In [606]:
count_ = np.arange(1,5)

In [607]:
df_s = pd.DataFrame()

In [608]:
print(count_)

[1 2 3 4]


In [609]:
for i in count_:
    tab_ = pd.read_html(str(tab_twy[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [610]:
twy_list = [x for x in df_s['Title']]

In [611]:
movie_title += twy_list

In [612]:
movie_title[-10:]

['Coming Home',
 'Fan Girl',
 'Isa Pang Bahaghari',
 'Magikland',
 'Mang Kepweng: Ang Lihim ng Bandanang Itim',
 'Pakboys Takusa',
 'Suarez: The Healing Priest',
 'Tagpuan',
 'The Boy Foretold by the Stars',
 'The Missing']

In [619]:
# complete list of movie 2000 to 2020

In [620]:
len(movie_title)

1322

In [621]:
len(set(movie_title)) # why does the number of movies became smaller? similar titles? 

1305